[package]
name = "serde_libconfig"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
derive = "1.0.0"
serde = { version = "1.0.197", features = ["derive"] }
thiserror = "1.0.58"
