---
name: Lint
# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  lint:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@clippy
      - run: cargo clippy --all-features --tests -- -Dwarnings -Dclippy::all
